### ISSUE TITLE
esp32: WebServer with HookFunction

### ISSUE THREAD

**Issue by pipi61** [d-a-v/ESPWebDAV#10]
Hi!
Testing Hooked_esp32.ino, but compile error:

Hooked_esp32:61:2: error: #error This sketch needs WebServer::HookFunction and WebServer::addHook

which library is used for webserver

Thank You

**Comment by luc-github** [comment]
the hook need a modified esp32 webserver and this part is not yet working https://github.com/d-a-v/ESPWebDAV/issues/5#issuecomment-763913288

The code I did for the moment : https://github.com/luc-github/arduino-esp32/commit/b5233795d7e61a2fc724397bb61db7065921bb41

**Comment by pipi61** [comment]
Thanks
