### ISSUE TITLE
Doesn't list filenames with spaces in them

### ISSUE THREAD

**Issue by idolpx** [d-a-v/ESPWebDAV#15]
Need to URL Encode fullResPath in ESPWebDAVCore::sendPropResponse() to correct the issue.

I will do a PR later when I am able if you'd like.

**Comment by d-a-v** [comment]
I am able to see spaces in file names.
Did you by misfortune exceed the file name length capacity ?

**Comment by idolpx** [comment]
No but after I url encode them it works fine.

**Comment by d-a-v** [comment]
Did you patch `ESPWebDAVCore::sendPropResponse()` to url-encode names ?

**Comment by idolpx** [comment]
Yes... I did.  Seemed to fix the issue for me.

**Comment by d-a-v** [comment]
Can you please share it as a PR ?
Is it committed on your fork ?

**Comment by idolpx** [comment]
I made the changes when adding it to meatloaf project.  I will test the additions you made for changing the web root and update my repo and send a pull request then.  :)

**Comment by idolpx** [comment]
Ok... sent a PR.  Just a one line fix.

**Comment by d-a-v** [comment]
closed per #18
