### ISSUE TITLE
Timeout never expires

### ISSUE THREAD

**Issue by pipi61** [d-a-v/ESPWebDAV#17]
Hi!
in ESPWebDAV.cpp this good?
...
1502 m_persistent_timer_ms = millis();
1503
1504 m_persistent = ((millis() - m_persistent_timer_ms) < m_persistent_timer_init_ms);
...
this timer never expires...
another suggestion:
the buffer size is very small
8899 char buf[128]; /// XXX use stream::to(): file.to(client);
and
1013 uint8_t buf[128];
if it changes to a higher value (I tried 1440 * 3), the transfer rate will increase significantly !!!

Thank You!
Istvan

**Comment by d-a-v** [comment]
Thanks for the suggestions !
I missed this notification.
>  this timer never expires...

I'll have to check

>  the buffer size is very small

True. In the meantime we have (on esp8266) `file.sendAll(client)`.
On esp32, the buffer can be increased, but storing 1440*3 bytes on stack is way too large.
Did you try with simply with TCP_MSS (1440) ?

**Comment by d-a-v** [comment]
Did you try the git version of this library (one year old) ?
Transfers had been optimized in the latest commits.

**Comment by pipi61** [comment]
Hi!
I modified, flashed and am using 20210919 version 2.1.3
I use data transfer to a 3D printer.
Removed the TFCARD from the printer, insert it into the ESP32CAM. The TF socket shares over the resistor network and the flat cable.
Normally the ESP32 is power on, but in reset mode, the printer uses the TFCARD.
If esp32 is power on, and works, then esp32 will use TFCARD and transfer 3d files on webdaw (in this case the printer does not see it)
this work properly
Thank You! Great works :)
![3d](https://user-images.githubusercontent.com/9288482/212977337-9662c90c-1757-4ef7-be52-5deea09a8f15.jpg)

**Comment by pipi61** [comment]
![3DPrinterHookup2 pipi](https://user-images.githubusercontent.com/9288482/212981198-f5456744-3c4a-4973-b6bc-e605db406048.jpg)
![ESPWebDAV1](https://user-images.githubusercontent.com/9288482/212981586-12106823-3e4c-437d-84d2-8ba6010837ba.png)

**Comment by d-a-v** [comment]
Thanks for the report !
