### ISSUE TITLE
ESP8266 - SDFS - compile error - Simple.ino

### ISSUE THREAD

**Issue by pagabee** [d-a-v/ESPWebDAV#19]
Hello,

there is a problem regarding the ESP8266 with SDFS.
I tried to compile the Simple.ino file without success.
Am I using the right version of the libraries/boards?

Simple.ino:

#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
**#include <SDFS.h>**
#include <ESPWebDAV.h>

#define HOSTNAME    "ESPWebDAV"

#ifndef STASSID
#define STASSID "ssid"
#define STAPSK "psk"
#endif

//FS& gfs = SPIFFS;_
//FS& gfs = LittleFS;
**FS& gfs = SDFS;**

![SdFat](https://user-images.githubusercontent.com/82469736/177937519-6032aa94-4b6f-4024-8d2d-07daef69d4d3.jpg)
![esp8266](https://user-images.githubusercontent.com/82469736/177937531-47b29968-5949-4e77-bc2d-67cf3b7c05b9.jpg)
![ESPWebDAV](https://user-images.githubusercontent.com/82469736/177939211-afbc60a9-4a22-4f59-ac0d-15e24a46f78f.jpg)

Compiler error message:
[error.txt](https://github.com/d-a-v/ESPWebDAV/files/9069744/error.txt)

**Comment by d-a-v** [comment]
Bill Greiman's excellent SdFat has been [adapted by Earle](https://github.com/esp8266/Arduino/tree/master/libraries) and is already included in esp8266 Arduino core.

Did you try without SdFat installed by Arduino library manager ?

The Simple.ino example with these changes compiles fine here:
```diff
diff --git a/examples/Simple/Simple.ino b/examples/Simple/Simple.ino
index 0fd0e99..707b6d6 100644
--- a/examples/Simple/Simple.ino
+++ b/examples/Simple/Simple.ino
@@ -51,7 +51,7 @@
 
 #include <ESP8266WiFi.h>
 #include <ESP8266mDNS.h>
-#include <LittleFS.h>
+#include <SDFS.h>
 #include <ESPWebDAV.h>
 
 #define HOSTNAME    "ESPWebDAV"
@@ -62,8 +62,8 @@
 #endif
 
 //FS& gfs = SPIFFS;
-FS& gfs = LittleFS;
-//FS& gfs = SDFS;
+//FS& gfs = LittleFS;
+FS& gfs = SDFS;
 
 //WiFiServerSecure tcp(443);
 WiFiServer tcp(80);
```

**Comment by pagabee** [comment]
The problem was caused by the SdFat library.
I had to delete it.

The SdFat is used by default:

Multiple libraries were found for "SdFat.h"

 Used: C:\Users\pagabee\Documents\Arduino\libraries\SdFat

 Not used: C:\Users\pagabee\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266SdFat

exit status 1


Thanks for your help!
