### ISSUE TITLE
micro sd card not detected.

### ISSUE THREAD

**Issue by shengyan** [d-a-v/ESPWebDAV#2]
I made a test board. PCB layout shown below.
![layout](https://user-images.githubusercontent.com/5512484/98943144-0359c100-252a-11eb-80d3-2c8cf1ac74bd.png)
PCB pins work fine and connection was confirmed using a test configuration as shown below (test board, micro SD card connector, micro SD card extender board).
![test board](https://user-images.githubusercontent.com/5512484/98946648-1ae77880-252f-11eb-936d-e02bdf7af334.jpg)

The issue is that 3D printer(Ender 3 V2 running custom marlin firmware) show  "no media" on LCD when plugin a micro SD card  using the test board as a adapter.

My guess is that the  SD card on the 3D printer is not running on SPI mode.

How can I confirm my guess and make adjustments, or, am I doing something wrong with the PCB design?

**Comment by d-a-v** [comment]
I can't tell.
You may have more help with this issue on the [original repository](https://github.com/ardyesp/ESPWebDAV) which was more focused on 3d printers and sdcard hijacking.

However I can tell this:
- try with a pure MMC card if you can find one. Those don't understand SD protocol.
- it may be a power issue - did you try to externally power the esp ?
(in that case you **must not wire** the vcc pin to the printer)
