### ISSUE TITLE
Write data failed: Stream::send: timeout

### ISSUE THREAD

**Issue by nightgryphon** [d-a-v/ESPWebDAV#20]
I'm trying to run an example Hooked.ino from latest cloned repo. 
The only change is debug enabled and some dir/files stored to LittleFS.
The board is Wemos D1 mini (ESP12-F). Client is windows 8.1 explorer.
I can read files but can not upload. Serial debug shows

`[ESPWebDAV.cpp:1537] parseRequest(): ############################################
[ESPWebDAV.cpp:1538] parseRequest(): >>>>>>>>>> RECV
[ESPWebDAV.cpp:1540] parseRequest(): method: PUT
[ESPWebDAV.cpp:1541] parseRequest():  url: /web/1/2/MKDOS318B.IMG
[ESPWebDAV.cpp:1549] parseRequest(): INPUT
[ESPWebDAV.cpp:1581] parseRequest(): 	Connection: Keep-Alive
[ESPWebDAV.cpp:1581] parseRequest(): 	User-Agent: Microsoft-WebDAV-MiniRedir/6.3.9600
[ESPWebDAV.cpp:1581] parseRequest(): 	If: (<ecdbafa3deadbeef>)
[ESPWebDAV.cpp:1581] parseRequest(): 	translate: f
[ESPWebDAV.cpp:1581] parseRequest(): 	Content-Length: 819200
[ESPWebDAV.cpp:1581] parseRequest(): 	Host: 172.16.21.247
[ESPWebDAV.cpp:1600] parseRequest(): <<<<<<<<<< RECV
[ESPWebDAV.cpp:473] handleRequest(): resource: '/web/1/2/MKDOS318B.IMG' is file
[ESPWebDAV.cpp:483] handleRequest(): m: PUT
[ESPWebDAV.cpp:484] handleRequest():  r: 1
[ESPWebDAV.cpp:485] handleRequest():  u: /web/1/2/MKDOS318B.IMG
[ESPWebDAV.cpp:1002] handlePut(): Processing Put
[ESPWebDAV.cpp:150] extractLockToken(): extracting lockToken from '(<ecdbafa3deadbeef>)'
[ESPWebDAV.cpp:165] extractLockToken(): found in [2..18[ (16)
[ESPWebDAV.cpp:175] extractLockToken(): IfToken: 'ecdbafa3deadbeef'
[ESPWebDAV.cpp:180] extractLockToken(): IfToken: path:0xecdbafa3 / owner:0xdeadbeef
[ESPWebDAV.cpp:195] allowed(): lock: testing '/web/1/2/MKDOS318B.IMG'
[ESPWebDAV.cpp:200] allowed(): lock: found lock, owner!
[ESPWebDAV.cpp:1014] handlePut(): create file '/web/1/2/MKDOS318B.IMG'
[ESPWebDAV.cpp:1031] handlePut(): /web/1/2/MKDOS318B.IMG - ready for data (819200 bytes)
recv: 'MKDOS318B.IMG': 0%
[ESPWebDAV.cpp:1055] handlePut(): WebDav: Put: file('MKDOS318B.IMG') error: Write data failed: Stream::send: timeout

[ESPWebDAV.cpp:1688] sendContent(): ---- content (40 bytes):
Write data failed: Stream::send: timeout
[ESPWebDAV.cpp:1715] sendContent(): OK with sendContent
[ESPWebDAV.cpp:1658] send(): send content (40 bytes):
Write data failed: Stream::send: timeout
[ESPWebDAV.cpp:1141] handleWriteError(): Write data failed: Stream::send: timeout
[WebDav4WebServer.cpp:24] operator()(): CLIENT_REQUEST_IS_HANDLED ('/web/1/2/MKDOS318B.IMG')
`

**Comment by d-a-v** [comment]
Can you still repeat this error with the latest release ?
