### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jajito** [d-a-v/ESPWebDAV#22]
HI, I have changet the 
#include <LITTLEFS.h>
to 
#include <LittleFS.h>
and every LITTLEFS to LITTLEFS, as sugested by the manteiner of the library.
I platformio no appears any error or problem, but when compiling it appears a problem in ESPWebDAV.cpp:

include/ESPWebDAV.cpp:1091:48: error: invalid conversion from 'char*' to 'const uint8_t*' {aka 'const unsigned char*'} [-fpermissive]

Am I doing something wrong or forgot something?.
Thanks ini advance

**Comment by serisman** [comment]
Changing line 1091 from: `auto numWrite = file.write(buf + written, numRead - written);`
to: `auto numWrite = file.write((uint8_t*)buf + written, numRead - written);`
seems to fix the compile error.

Still testing if this actually works or not...

UPDATE: it seems to work just fine!

**Comment by jajito** [comment]
Now it compiles!
Thanks serisman!

**Comment by jajito** [comment]
But doesn't work.
Doesn't send info of the files or folders to the FTP client...
The rest works ok...

**Comment by d-a-v** [comment]
> But doesn't work.
> Doesn't send info of the files or folders to the FTP client...


Can you please give more input about your issue ?

**Comment by d-a-v** [comment]
> Changing line 1091 from: `auto numWrite = file.write(buf + written, numRead - written);` to: 
> `auto numWrite = file.write((uint8_t*)buf + written, numRead - written);`

fixed by #23
