### ISSUE TITLE
Please provide an example for using SD card instead of internal memory

### ISSUE THREAD

**Issue by heinerolli** [d-a-v/ESPWebDAV#24]
@d-a-v Thank you 1st of all for providing this 'enhanced' ESPWebDav system!
(I start a new 'issue' for this to not be mingled with the unfriendly 'no documentation...' issue)

I got it to run with the std. example using LittleFS, however, I would like to use an SD card....
-> Could you please provide an example based on your library?
(Preferably also stating the respective library and ESP8266 core *versions* 
I did try the 'simple' example from ardyesp, but I get a compile error:

```
Simple:115:11: error: 'class ESPWebDAV' has no member named 'init'
  115 |   if(!dav.init(SD_CS, SPI_FULL_SPEED, 80))   {
All the best.
```
P.S. I am using an ESP8266; I can switch to ESP32 if that makes it easier

**Comment by d-a-v** [comment]
The [Hooked](https://github.com/d-a-v/ESPWebDAV/blob/956defa15115837b0d1fc8fd8a5876dea9eab6bb/examples/Hooked/Hooked.ino#L68-L93) example has been updated (for esp8266 only).

Please report if you have issues.
